import { useEffect, useId, useRef, useState } from 'react'

// TradingView's official "Advanced Chart" widget (free, no API key or
// account) — the JSON-config-in-<script> embed generated by their widget
// builder at https://www.tradingview.com/widget/advanced-chart/. The
// tv.js constructor method (new TradingView.widget({...})) was tried
// first, but its chart iframe (s.tradingview.com/widgetembed) was
// consistently cancelled by the browser in testing (reproduced in
// incognito, no console errors) — never got past loading at all. This
// method actually renders (candles, volume, price, date-range toolbar).
//
// Known limitations of this embed variant, confirmed by testing:
// - `studies`/`studies_overrides` are accepted and do reach the iframe's
//   config (visible in its URL hash), but the studies never actually
//   attach to the chart — no legend row, no overlay line at any zoom
//   level. So the green price-line / red EMA(10) overlay described below
//   doesn't currently render; only the candles show. Root cause not
//   pinned down — TradingView's own bundle logs a stray
//   `"[object Object]" is not valid JSON` console error on every load
//   (reproduces even in a bare static HTML page with no React involved),
//   which may be related.
const EMBED_SCRIPT_SRC = 'https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js'

// Reusable embed for TradingView's free Advanced Chart widget. Symbol and
// studies are props (not hardcoded) so this can be dropped in for any
// ticker/study combination. containerId defaults to a per-instance React id
// so multiple charts can coexist on the same page without collisions.
export default function TradingViewWidget({
  symbol = 'NASDAQ:QQQ',
  interval = 'D',
  // "Moving Average" (SMA) with length 1 just traces the raw close price —
  // the standard trick for a distinctly-colorable "price line" overlay on
  // top of candles, since the main series itself can only be one style
  // (candles OR line, not both) and its color otherwise follows candle
  // up/down state rather than a fixed color.
  studies = ['MASimple@tv-basicstudies', 'MAExp@tv-basicstudies'],
  studiesOverrides = {
    'moving average.length': 1,
    'moving average.plot.color': '#00c896', // green, matches --green
    'moving average exponential.length': 10,
    'moving average exponential.plot.color': '#ff4c4c', // red, matches --red
  },
  height = 550,
  containerId,
}) {
  const reactId = useId().replace(/[^a-zA-Z0-9]/g, '')
  const widgetId = containerId || `tv_widget_${reactId}`
  const containerRef = useRef(null)
  const [ready, setReady] = useState(false)
  const [failed, setFailed] = useState(false)

  useEffect(() => {
    const container = containerRef.current
    let cancelled = false
    setReady(false)
    setFailed(false)
    if (container) container.innerHTML = ''

    // The embed script can hang instead of erroring outright (blocked by a
    // content/ad blocker, flaky network, etc.) — without this, a failure
    // leaves the skeleton spinning forever with no feedback.
    const timeout = setTimeout(() => {
      if (!cancelled) setFailed(true)
    }, 10000)

    // Deferring the actual <script> insertion by a tick — rather than doing
    // it inline above — matters because React StrictMode double-invokes
    // this effect in dev (mount → cleanup → mount, synchronously, before any
    // timer fires). A classic <script src> already begun fetching keeps
    // executing even after being removed from the DOM, so the phantom first
    // mount's script would still run against a detached tree and throw
    // (querySelector on null / JSON.parse on the wrong node). Deferring lets
    // the synchronous cleanup flip `cancelled` first, so the phantom mount's
    // script is never created in the first place.
    const setupId = setTimeout(() => {
      if (cancelled || !container) return

      const config = {
        autosize: true,
        symbol,
        interval,
        timezone: 'Etc/UTC',
        theme: 'dark',
        style: '1', // Candles — price line and EMA(10) are overlaid as studies below
        locale: 'en',
        withdateranges: true, // shows the built-in 1D/1M/3M/YTD/1Y/5Y/ALL range toolbar
        range: '12M',
        allow_symbol_change: true,
        studies,
        studies_overrides: studiesOverrides,
        support_host: 'https://www.tradingview.com',
      }

      // Matches TradingView's official generated markup exactly: the
      // ".tradingview-widget-container__widget" div and the <script> are
      // siblings, both children of the outer container.
      const widgetDiv = document.createElement('div')
      widgetDiv.className = 'tradingview-widget-container__widget'
      widgetDiv.style.height = '100%'
      widgetDiv.style.width = '100%'

      const script = document.createElement('script')
      script.src = EMBED_SCRIPT_SRC
      script.async = true
      script.type = 'text/javascript'
      script.text = JSON.stringify(config)
      script.onload = () => {
        // This embed type has no ready-callback — the script itself finishing
        // is the best available readiness signal for swapping out the skeleton.
        if (!cancelled) {
          clearTimeout(timeout)
          setReady(true)
        }
      }
      script.onerror = () => {
        if (!cancelled) {
          clearTimeout(timeout)
          setFailed(true)
        }
      }

      container.appendChild(widgetDiv)
      container.appendChild(script)
    }, 0)

    return () => {
      cancelled = true
      clearTimeout(timeout)
      clearTimeout(setupId)
      if (container) container.innerHTML = ''
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [symbol, interval, widgetId, JSON.stringify(studies), JSON.stringify(studiesOverrides)])

  const heightVar = { '--tv-height': `${height}px` }

  if (failed) {
    return (
      <div className="tv-widget-wrap tv-widget-fallback" style={heightVar}>
        <span>Chart failed to load.</span>
        <a href={`https://www.tradingview.com/chart/?symbol=${encodeURIComponent(symbol)}`} target="_blank" rel="noopener noreferrer">
          View {symbol} on TradingView →
        </a>
      </div>
    )
  }

  return (
    <div id={widgetId} className="tv-widget-wrap" style={heightVar}>
      {!ready && <div className="tv-widget-skeleton" />}
      <div
        ref={containerRef}
        className="tradingview-widget-container"
        style={{ height: '100%', width: '100%', visibility: ready ? 'visible' : 'hidden' }}
      />
    </div>
  )
}
