import { useEffect, useId, useRef, useState } from 'react'

// TradingView's official "Advanced Chart" widget (free, no API key or
// account) — the JSON-config-in-<script> embed generated by their widget
// builder at https://www.tradingview.com/widget/advanced-chart/, not the
// older tv.js constructor API.
const EMBED_SCRIPT_SRC = 'https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js'

// Reusable embed for TradingView's free Advanced Chart widget. Symbol and
// studies are props (not hardcoded) so this can be dropped in for any
// ticker/study combination. containerId defaults to a per-instance React id
// so multiple charts can coexist on the same page without collisions.
export default function TradingViewWidget({
  symbol = 'NASDAQ:QQQ',
  interval = 'D',
  studies = ['MAExp@tv-basicstudies'],
  studiesOverrides = { 'moving average exponential.length': 10 },
  height = 550,
  containerId,
}) {
  const reactId = useId().replace(/[^a-zA-Z0-9]/g, '')
  const widgetId = containerId || `tv_widget_${reactId}`
  const widgetRef = useRef(null)
  const [ready, setReady] = useState(false)
  const [failed, setFailed] = useState(false)

  useEffect(() => {
    let cancelled = false
    setReady(false)
    setFailed(false)
    if (widgetRef.current) widgetRef.current.innerHTML = ''

    // The embed script can hang instead of erroring outright (blocked by a
    // content/ad blocker, flaky network, etc.) — without this, a failure
    // leaves the skeleton spinning forever with no feedback.
    const timeout = setTimeout(() => {
      if (!cancelled) setFailed(true)
    }, 10000)

    const config = {
      autosize: true,
      symbol,
      interval,
      timezone: 'Etc/UTC',
      theme: 'dark',
      style: '1',
      locale: 'en',
      withdateranges: true, // shows the built-in 1D/1M/3M/YTD/1Y/5Y/ALL range toolbar
      range: '12M',
      allow_symbol_change: true,
      studies,
      studies_overrides: studiesOverrides,
      support_host: 'https://www.tradingview.com',
    }

    const script = document.createElement('script')
    script.src = EMBED_SCRIPT_SRC
    script.async = true
    script.type = 'text/javascript'
    script.text = JSON.stringify(config)
    script.onload = () => {
      // This embed type has no ready-callback — the script itself finishing
      // is the best available readiness signal for swapping out the skeleton.
      if (!cancelled) {
        clearTimeout(timeout)
        setReady(true)
      }
    }
    script.onerror = () => {
      if (!cancelled) {
        clearTimeout(timeout)
        setFailed(true)
      }
    }

    if (widgetRef.current) widgetRef.current.appendChild(script)

    return () => {
      cancelled = true
      clearTimeout(timeout)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [symbol, interval, widgetId, JSON.stringify(studies), JSON.stringify(studiesOverrides)])

  const heightVar = { '--tv-height': `${height}px` }

  if (failed) {
    return (
      <div className="tv-widget-wrap tv-widget-fallback" style={heightVar}>
        <span>Chart failed to load.</span>
        <a href={`https://www.tradingview.com/chart/?symbol=${encodeURIComponent(symbol)}`} target="_blank" rel="noopener noreferrer">
          View {symbol} on TradingView →
        </a>
      </div>
    )
  }

  return (
    <div id={widgetId} className="tv-widget-wrap" style={heightVar}>
      {!ready && <div className="tv-widget-skeleton" />}
      <div className="tradingview-widget-container" style={{ height: '100%', width: '100%', visibility: ready ? 'visible' : 'hidden' }}>
        <div className="tradingview-widget-container__widget" ref={widgetRef} style={{ height: '100%', width: '100%' }} />
      </div>
    </div>
  )
}
